### ISSUE TITLE
Doesn't work on Middleman 4.2

### ISSUE THREAD

**Issue by Nowaker** [yterajima/middleman-slim#7]
```
nowaker@nwkr-desktop ~/projekty/virtkick/website (git)-[master] % bundle exec middleman s
/home/nowaker/.rvm/gems/ruby-2.3.3/gems/middleman-slim-0.2.2/lib/middleman-slim/template.rb:1:in `require': cannot load such file -- middleman-core/templates (LoadError)
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/middleman-slim-0.2.2/lib/middleman-slim/template.rb:1:in `<top (required)>'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/middleman-slim-0.2.2/lib/middleman-slim.rb:3:in `require'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/middleman-slim-0.2.2/lib/middleman-slim.rb:3:in `<top (required)>'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/runtime.rb:91:in `require'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/runtime.rb:86:in `each'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/runtime.rb:86:in `block in require'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/runtime.rb:75:in `each'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/runtime.rb:75:in `require'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler.rb:106:in `require'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/load_paths.rb:35:in `setup_bundler'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/load_paths.rb:15:in `setup_load_paths'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/middleman-cli-4.2.0/bin/middleman:10:in `<top (required)>'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/bin/middleman:22:in `load'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/bin/middleman:22:in `<main>'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by yterajima** [comment]
Project Template has been changed from Middleman v4. https://middlemanapp.com/advanced/project_templates/

Please try it with the following procedure.
```
$ middleman init YOUR_PROJECT -T yterajima/middleman-slim
$ cd YOUR_PROJECT
$ bundle install --path vendor/bundle
$ bundle exec middleman s
```

**Comment by Nowaker** [comment]
@yterajima It doesn't seem to work. Same error.

```
nowaker@nwkr-laptop ~/projekty/ruby/geozone/x (git)-[master] % middleman init geozone -T yterajima/middleman-slim
/home/nowaker/.rvm/gems/ruby-2.3.3/gems/middleman-slim-0.2.2/lib/middleman-slim/template.rb:1:in `require': cannot load such file -- middleman-core/templates (LoadError)
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/middleman-slim-0.2.2/lib/middleman-slim/template.rb:1:in `<top (required)>'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/middleman-slim-0.2.2/lib/middleman-slim.rb:3:in `require'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/middleman-slim-0.2.2/lib/middleman-slim.rb:3:in `<top (required)>'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/runtime.rb:91:in `require'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/runtime.rb:86:in `each'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/runtime.rb:86:in `block in require'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/runtime.rb:75:in `each'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/runtime.rb:75:in `require'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler.rb:106:in `require'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/load_paths.rb:35:in `setup_bundler'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/middleman-core-4.2.0/lib/middleman-core/load_paths.rb:15:in `setup_load_paths'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/gems/middleman-cli-4.2.0/bin/middleman:10:in `<top (required)>'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/bin/middleman:22:in `load'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/bin/middleman:22:in `<main>'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
        from /home/nowaker/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by yterajima** [comment]
uhm...

middleman-slim-0.2.2 is too old for Middleman v4. Please uninstall middleman-slim-0.2.2.

if not fixed this problem, your Middleman version may be old(v3.xx).

**Comment by Nowaker** [comment]
I also use the latest version of Middleman. You can see the version number in my stacktrace.

And 0.2.2 is the latest version too: https://rubygems.org/gems/middleman-slim. 

Do you mean middleman-slim has to be **deleted** from the system, or your template won't work? If so, this is pretty bad. Some of my other projects use Middleman v3 so every time I work on them and run bundle install the gem will get installed.

**Comment by Nowaker** [comment]
Okay... 0.3.0 is in GitHub but 0.2.2 in Rubygems.org. Can you push the latest version to Rubygems? Thank you. 👍 

- https://github.com/yterajima/middleman-slim/releases
- https://rubygems.org/gems/middleman-slim

**Comment by Nowaker** [comment]
Hi @yterajima. I was able to track down the real issue. Here's the thing: **middleman-slim gem is no longer needed for Middleman v4 because support for Slim is included out of the box**.

**Comment by yterajima** [comment]
Thanks to track down.

middleman-slim is definitely unnecessary since it is a simple project template from v4. 
You can just use `require' slim` in config.rb.
